version: "3.9"
services:

  db-init:
    image: postgres:14
    volumes:
      - ./twitter-db-data:/var/lib/postgresql/data
    entrypoint:
      - sh
      - -c
      - |
        chown -R 2000:2000 /var/lib/postgresql/data

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    image: postgres:14
    user: 2000:2000
    restart: always
    container_name: 'db'
    command: postgres -c 'max_connections=200' -c 'client_connection_check_interval=60000'
    environment:
        POSTGRES_DB: 'twitter'
        POSTGRES_USER: 'twitter'
        POSTGRES_PASSWORD: 'ceWb1MeLBEeOIfk65gU8EjF8'
    ports:
      - 7432:5432
    volumes:
      - ./twitter-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twitter -d twitter"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  twitter:
    image: ghcr.io/black-web-dev/cascadia-twitter:latest
    container_name: twitter
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: postgres://twitter:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/twitter?schema=public&connection_limit=10&pool_timeout=2
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: cascadia
      GOOGLE_CLIENT_ID: 391616151250-i942casg5chgefg0veh9f3pifbdkactb.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      NEXT_PUBLIC_SUPABASE_URL: https://bzquotasibuzwyhlneqp.supabase.co
      NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6cXVvdGFzaWJ1end5aGxuZXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDI0Njc3NDYsImV4cCI6MjAxODA0Mzc0Nn0.I5cyoukJUdp5s4gC6C8ZP7A9NyMtvkIxwbl2uqlE_ms
      NODE_ENV: production
      REDIS_URL: https://us1-witty-bulldog-41625.upstash.io
      REDIS_TOKEN: AaKZACQgZGJlMGQ0NDktZTMwYy00YTVmLWExZmEtYTVjNTJjMTJlOTFjYmM3MWYwZTA5M2FlNGEwM2E1ZGNjZDE4ZWIwMWQ5OWI=
      PORT: 3000
    ports:
      - "3000:3000"
