version: "3.9"
services:
  twitter:
    image: ghcr.io/black-web-dev/cascadia-twitter:main
    container_name: twitter
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/database?schema=public&connection_limit=10&pool_timeout=2
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: cascadia
      GOOGLE_CLIENT_ID: 391616151250-i942casg5chgefg0veh9f3pifbdkactb.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 
      NEXT_PUBLIC_SUPABASE_URL: https://bzquotasibuzwyhlneqp.supabase.co
      NEXT_PUBLIC_SUPABASE_ANON_KEY: 
      NODE_ENV: production
      REDIS_URL: https://us1-witty-bulldog-41625.upstash.io
      REDIS_TOKEN: 
      PORT: 3000
    ports:
      - "3000:3000"
