version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  splitmate-app:
    image: splitmate
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    volumes:
      - postgres-data:/app/postgres-data
    
    environment:
      DATABASE_URL: postgres://user:password@localhost:5432/mydatabase?schema=public&connection_limit=10&pool_timeout=2
    ports:
      - 3000:3000
volumes:
  postgres-data: