blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/orgs/cascadiafoundation/discussions
    about: Ask questions and discuss topics with other community members
  - name: Join our Discord Server
    url: https://discord.gg/cascadiafoundation
    about: The official Cascadia Discord community